
exclude:
  - "/vendor/"
  - "Gemfile"
  - "Gemfile.lock"
  - "README.md"
  - "LICENSE.md"
  - "*.gemspec"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"


# Site settings
title: "American Literacy Council"
subtitle: "Advocates for Simplified Spelling"
url: "http://https://americanliteracy.github.io" # the base hostname & protocol for your site
# baseurl: "/the/subpath/of/your/site" # Set this value to "" if you want your site to be root
baseurl: ""
cover: "/assets/cover.png"
logo: "/assets/logo.png"

# Build settings
markdown: kramdown

# Google analytics
# ga_tracking_id: "UA-XXXX-1"

# Category descriptions (for archive pages)
descriptions:
  - cat: jekyll
    desc: "Posts describing Jekyll setup techniques."

  - cat: dummy
    desc: "Just some placeholder posts, lorem ipsum and the rest."

# Site navigation
navigation_header:
- title: Home
  titleSS: Hoem
  url: /index
  urlSS: /ss/index/
- title: SoundSpel
  titleSS: SoundSpel
  url: /ts/soundspel/
  urlSS: /ss/soundspel/
- title: Tools
  titleSS: Tools
  url: /ts/tools/
  urlSS: /ss/tools/
- title: History
  titleSS: History
  url: /ts/history/
  urlSS: /ss/history/
- title: Publications
  titleSS: Publications
  url: /ts/publications/
  urlSS: /ss/publications/
- title: contact
  titleSS: contact
  url: /ts/contact/
  urlSS: /ss/contact/
